apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: trofimov20260527
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: recipehub
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
