apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: trofimov20260527
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: recipehub
type: Opaque
stringData:
  POSTGRES_DB: recipehub
  POSTGRES_USER: recipehub
  POSTGRES_PASSWORD: recipehub_password
