apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: trofimov20260527
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/part-of: recipehub
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: recipehub-logs
        static_configs:
          - targets:
              - localhost
            labels:
              app: recipehub
              service: symfony
              platform: minikube
              __path__: /var/log/recipehub/*.log
